// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaIngresoBackend.Repository;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(NewshoreAirDbContext))]
    partial class NewshoreAirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Fligth", b =>
                {
                    b.Property<int>("FligthId")
                        .HasColumnType("int")
                        .HasColumnName("fligth_id");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination");

                    b.Property<string>("Origin")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origin");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("TransportId")
                        .HasColumnType("int")
                        .HasColumnName("transport_id");

                    b.HasKey("FligthId")
                        .HasName("PK__fligth__76261301FBEDCE68");

                    b.HasIndex("TransportId");

                    b.ToTable("fligth");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Journey", b =>
                {
                    b.Property<int>("JourneyId")
                        .HasColumnType("int")
                        .HasColumnName("journey_id");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination");

                    b.Property<string>("Origin")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origin");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("JourneyId")
                        .HasName("PK__journey__B6E9049CA1960992");

                    b.ToTable("journey");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.JourneyFlight", b =>
                {
                    b.Property<int>("JourneyFlightId")
                        .HasColumnType("int")
                        .HasColumnName("journey_flight_id");

                    b.Property<int>("FligthId")
                        .HasColumnType("int")
                        .HasColumnName("fligth_id");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int")
                        .HasColumnName("journey_id");

                    b.HasKey("JourneyFlightId")
                        .HasName("PK__journey___EE01FF5AE489D814");

                    b.HasIndex("FligthId");

                    b.HasIndex("JourneyId");

                    b.ToTable("journey_flight");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Transport", b =>
                {
                    b.Property<int>("TransportId")
                        .HasColumnType("int")
                        .HasColumnName("transport_id");

                    b.Property<string>("FligthCarrier")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fligth_carrier");

                    b.Property<string>("FligthCarrierNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fligth_carrier_number");

                    b.HasKey("TransportId")
                        .HasName("PK__transpor__A17E3277E9A38D81");

                    b.ToTable("transport");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Fligth", b =>
                {
                    b.HasOne("PruebaIngresoBackend.Repository.Models.Transport", "Transport")
                        .WithMany("Fligths")
                        .HasForeignKey("TransportId")
                        .IsRequired()
                        .HasConstraintName("FK__fligth__transpor__4D94879B");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.JourneyFlight", b =>
                {
                    b.HasOne("PruebaIngresoBackend.Repository.Models.Fligth", "Fligth")
                        .WithMany("JourneyFlights")
                        .HasForeignKey("FligthId")
                        .IsRequired()
                        .HasConstraintName("FK__journey_f__fligt__52593CB8");

                    b.HasOne("PruebaIngresoBackend.Repository.Models.Journey", "Journey")
                        .WithMany("JourneyFlights")
                        .HasForeignKey("JourneyId")
                        .IsRequired()
                        .HasConstraintName("FK__journey_f__journ__534D60F1");

                    b.Navigation("Fligth");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Fligth", b =>
                {
                    b.Navigation("JourneyFlights");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Journey", b =>
                {
                    b.Navigation("JourneyFlights");
                });

            modelBuilder.Entity("PruebaIngresoBackend.Repository.Models.Transport", b =>
                {
                    b.Navigation("Fligths");
                });
#pragma warning restore 612, 618
        }
    }
}
